"""
Test scripts for the FastAPI application, focusing on the /health endpoint changes.

Generated by the Test Generator Agent.
"""

import pytest
from fastapi.testclient import TestClient
from backend.main import app, health  # Assuming the app is in backend/main.py

# --- Fixtures ---

@pytest.fixture(scope="module")
def test_client() -> TestClient:
    """
    Provides a TestClient instance for making requests to the FastAPI app.
    """
    client = TestClient(app)
    yield client


# --- Unit Tests ---

@pytest.mark.unit
def test_health_function_returns_correct_dict():
    """
    Unit test for the health() function in isolation.

    Verifies that the function returns the expected dictionary, including the new version field.
    This test does not involve the web server or routing.
    """
    # Act
    result = health()

    # Assert
    expected = {"status": "ok", "version": "1.0.0"}
    assert result == expected
    assert isinstance(result["status"], str)
    assert isinstance(result["version"], str)


# --- Integration and Contract Tests ---

@pytest.mark.integration
def test_health_endpoint_returns_200_ok(test_client: TestClient):
    """
    Integration test to verify the /health endpoint is reachable and returns a 200 OK status.
    """
    # Act
    response = test_client.get("/health")

    # Assert
    assert response.status_code == 200


@pytest.mark.contract
def test_health_endpoint_response_contract_and_values(test_client: TestClient):
    """
    API contract test for the /health endpoint.

    Verifies:
    1. The status code is 200.
    2. The response body contains the correct keys ('status', 'version').
    3. The data types of the values are correct (string).
    4. The values match the expected content.
    """
    # Act
    response = test_client.get("/health")

    # Assert status code
    assert response.status_code == 200

    # Assert response body
    data = response.json()
    expected_response = {"status": "ok", "version": "1.0.0"}
    assert data == expected_response

    # Assert schema and types
    assert "status" in data
    assert "version" in data
    assert isinstance(data["status"], str)
    assert isinstance(data["version"], str)


@pytest.mark.integration
def test_health_endpoint_rejects_unsupported_methods(test_client: TestClient):
    """
    Negative integration test to ensure the /health endpoint only accepts GET requests.

    It checks that other common HTTP methods like POST, PUT, and DELETE are correctly
    rejected with a 405 "Method Not Allowed" status code.
    """
    # Act & Assert
    response_post = test_client.post("/health", json={"data": "test"})
    assert response_post.status_code == 405

    response_put = test_client.put("/health", json={"data": "test"})
    assert response_put.status_code == 405

    response_delete = test_client.delete("/health")
    assert response_delete.status_code == 405

# --- Security Tests ---

# Note: No security tests are generated for this change as the /health endpoint
# does not accept any user input, making it immune to common input-based
# vulnerabilities like SQL Injection or XSS.

# --- UI Tests ---

# Note: No UI tests are generated as this is a backend API change with no
# direct impact on the user interface.